server:
  port: 8001
  servlet:
    context-path: /member
spring:
  datasource:
    url: jdbc:mysql://rm-wz9st1995248til6f1o.rwlb.rds.aliyuncs.com/train_member?characterEncoding=UTF-8&autoReconnect=true
    username: root                    # 用户名
    password: 123456Po*                # 密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL驱动

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.zjl.train.member.mapper: trace
