server:
  port: 8000  # 设置网关服务的端口号为 8000


spring:
  cloud:
    gateway:
      routes:
        - id: member  # 路由 ID，用于标识这个路由规则
          uri: http://127.0.0.1:8001  # 指定请求将转发到的目标 URI
          predicates:
            - Path=/member/**  # 匹配路径为 /member/** 的请求，并应用此路由

        - id: business  # 新增business模块路由 ID
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/business/**  # 匹配路径为 /business/** 的请求，并应用此路由

        - id: batchtask  # 新增batchtask模块路由 ID
          uri: http://127.0.0.1:8003
          predicates:
            - Path=/batch/**  # 匹配路径为 /batch/** 的请求，并应用此路由

      # 全局跨域配置，允许跨域访问
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:9000"
              - "http://localhost:9001"
              - "http://localhost:9002"
              - "http://localhost:9003"
              - "http://localhost:9004"
              - "http://192.168.10.8:9000"
            allowed-headers: "*"
            allowed-methods: "*"
            allow-credentials: true
            max-age: 3600
  application:
    name: train-gateway


